service, controller class initial setting
711skhu/api pull request #2
Opened 2019-04-06 09:22 UTC by lwiiiiii

service, controller 클래스입니다.

2019-04-06 09:50 UTC, shouwn requested changes
https://github.com/711skhu/admin/pull/3#pullrequestreview-223535606

코멘트에 적은 내용과 마찬가지입니다.

여기서는 CourseServiceorApi 가 이름에 좋겠네요.

2019-04-09 10:15 UTC, KimJye approved these changes

2019-04-09 10:43 UTC, yjll1019 approved these changes

2019-04-09 14:11 UTC, shouwn commented
entity와 통일성을 위해
service - member
service - problem
으로 패키지 형식을 맞춰주세요

2019-04-10 05:07 UTC, shouwn approved these changes

2019-04-10 05:32 UTC, KimJye approved these changes

2019-04-10 05:33 UTC, KimJye approved these changes

2019-04-10 05:36 UTC, merged